"""Every project on the site. Add or edit an entry here, then run `python3 build.py`."""

GAMEBOX = "Immersive Gamebox"
GAMEBOX_ROLE = "Lead designer · Director of Experience Design"
GAMEBOX_TECH = ["Motion tracking", "LiDAR touch walls", "Projection"]

PROJECTS = [
    {
        "slug": "batman",
        "title": "Batman",
        "client": GAMEBOX,
        "group": "gamebox",
        "role": GAMEBOX_ROLE,
        "players": "Up to 6",
        "tech": GAMEBOX_TECH,
        "colour": "yellow",
        "hero": "batman-hero.jpg",
        "summary": "A one-hour co-op adventure in the Batcave: solve puzzles, battle villains and drive the Batmobile to save Gotham.",
        "about": [
            "Batman is a full-hour cooperative adventure for a Gamebox room. Players team up in the Batcave to solve puzzles, fight Gotham's villains and take the wheel of the Batmobile, all through 3D graphics and animated storytelling that respond to their movement around the room.",
        ],
        "did": [
            "Designed the game from start to finish and wrote the full design documents",
            "Built high-fidelity prototypes to test puzzles, fights and the Batmobile section",
            "Directed the art and supported the development team through production",
            "Worked directly with Warner Bros and the Batman design team through approvals",
        ],
        "gallery": ["batman-driving.jpg", "batman-3.jpg"],
        "links": [("Play it at Immersive Gamebox", "https://www.immersivegamebox.com/en-GB/batman")],
    },
    {
        "slug": "ghostbusters",
        "title": "Ghostbusters: The Cursed Collection",
        "short": "Ghostbusters",
        "client": GAMEBOX,
        "group": "gamebox",
        "role": GAMEBOX_ROLE,
        "players": "Up to 6",
        "tech": GAMEBOX_TECH,
        "colour": "green",
        "hero": "ghostbusters-1.jpg",
        "summary": "Strap on a proton pack and recover cursed artefacts across a haunted New York.",
        "about": [
            "In Ghostbusters: The Cursed Collection, players join the team in a New York overrun by spirits. They recover cursed artefacts, catch mischievous ghosts and take on Stay Puft, with proton streams aimed by body tracking.",
            "The HUD frames the game as a live broadcast, with a score, a viewer count and a marker for each player's stream. Boss health bars keep the whole group aiming at a shared target.",
        ],
        "did": [
            "Designed the game, its levels and the boss encounters",
            "Designed the HUD and interface for six players aiming at the same wall",
            "Prototyped and playtested the aiming and capture mechanics",
        ],
        "gallery": ["ghostbusters-2.jpg", "ghostbusters-3.jpg"],
        "links": [("Play it at Immersive Gamebox", "https://www.immersivegamebox.com/en-GB/ghostbusters")],
    },
    {
        "slug": "tetris-1991",
        "title": "Tetris 1991",
        "client": GAMEBOX,
        "group": "gamebox",
        "role": GAMEBOX_ROLE,
        "players": "Up to 6",
        "tech": GAMEBOX_TECH,
        "colour": "cyan",
        "status": "No longer running",
        "hero": "tetris-room.jpg",
        "summary": "In 1991 a hacked Game Boy turns the world into Tetriminos, and it's up to you to reset it.",
        "about": [
            "A tech genius hacks a handheld Tetris game, and suddenly everything and everyone is turning into Tetriminos. Groups of up to six play five human-sized Tetris mini-games solo, in pairs and together to put the world back to non-cubular shapes.",
            "The look is authentic early-90s handheld. The challenge was keeping the retro feel while staying readable on a wall-sized screen in the middle of a physical game.",
        ],
        "did": [
            "Designed the story, the five mini-games and the flow of the whole session",
            "Set the 1991 art direction and designed the interface",
            "Prototyped and playtested the human-sized Tetris mechanics",
        ],
        "gallery": [],
        "links": [
            ("Gameplay video", "https://www.youtube.com/watch?v=Xj1c2mwmndU"),
            ("Launch press", "https://www.amusementsandattractions.com/attractions/news/immersive-gamebox-adds-tetris-game"),
        ],
    },
    {
        "slug": "escape-ai",
        "title": "Escape AI",
        "client": GAMEBOX,
        "group": "gamebox",
        "role": GAMEBOX_ROLE,
        "players": "Up to 6",
        "tech": GAMEBOX_TECH,
        "colour": "pink",
        "hero": "escape-ai-2.jpg",
        "summary": "A cold case for the 22nd century: solve a decades-old murder with CCTV reconstruction and an AI guide.",
        "about": [
            "Escape AI is an immersive escape room. Players investigate a decades-old murder wrapped in a tech magnate's secrets, using Hindsight's CCTV reconstruction and their AI guide, Aya.",
        ],
        "did": [
            "Designed the mystery, the puzzles and the story",
            "Designed how players interact with the reconstruction tools on the walls",
            "Prototyped and playtested the puzzle chain",
        ],
        "gallery": ["escape-ai-1.jpg", "escape-ai-3.jpg"],
        "links": [("Play it at Immersive Gamebox", "https://www.immersivegamebox.com/en-GB/escape-ai")],
    },
    {
        "slug": "floor-is-lava",
        "title": "Floor is Lava",
        "client": GAMEBOX,
        "group": "gamebox",
        "role": GAMEBOX_ROLE,
        "players": "Up to 6",
        "tech": GAMEBOX_TECH,
        "colour": "orange",
        "hero": "floor-is-lava-hero.jpg",
        "summary": "Work together to dodge the lava and climb the volcano.",
        "about": [
            "Based on the hit TV format, Floor is Lava turns the Gamebox floor and walls into a volcano. The team has to move together to dodge the rising lava and make it to the top.",
        ],
        "did": [
            "Designed the game and its levels",
            "Balanced the challenge for families and mixed-age groups",
            "Prototyped and playtested the movement mechanics",
        ],
        "gallery": ["floor-is-lava-2.jpg"],
        "links": [("Play it at Immersive Gamebox", "https://www.immersivegamebox.com/en-GB/floor-is-lava")],
    },
    {
        "slug": "football-arcade",
        "title": "Football Arcade",
        "client": GAMEBOX,
        "group": "gamebox",
        "role": GAMEBOX_ROLE,
        "players": "Up to 6",
        "tech": GAMEBOX_TECH,
        "colour": "blue",
        "year": "2026",
        "hero": "football-hero.jpg",
        "summary": "A limited-time football festival: keepy-uppies, team battles and streaks, played with your whole body.",
        "about": [
            "Football Arcade was a limited-time run of football skill games for the world's biggest football tournament. Teams go head to head in games like Keepy Uppy, with scoreboards that are big enough to read mid-game: team scores, a timer, and current and best streaks.",
        ],
        "did": [
            "Designed the collection of football skill games",
            "Designed the room-scale scoreboard and HUD",
            "Prototyped and playtested the ball physics and team play",
        ],
        "gallery": ["football-1.jpg", "football-3.jpg"],
        "links": [("Immersive Gamebox", "https://www.immersivegamebox.com/en-GB/football-arcade")],
    },
    {
        "slug": "box-party",
        "title": "Box Party",
        "client": GAMEBOX,
        "group": "gamebox",
        "role": GAMEBOX_ROLE,
        "players": "Up to 6",
        "tech": GAMEBOX_TECH,
        "colour": "purple",
        "hero": "box-party-hero.jpg",
        "summary": "Battle, race and puzzle through wild, physical party games to top the leaderboard.",
        "about": [
            "Box Party is a collection of fast, highly physical party games, with different games each visit. Groups battle, race and puzzle their way up the Gamebox leaderboard.",
        ],
        "did": [
            "Designed the party games and how the session flows between them",
            "Designed the leaderboard and competitive structure",
            "Prototyped and playtested each game with real groups",
        ],
        "gallery": [],
        "links": [("Play it at Immersive Gamebox", "https://www.immersivegamebox.com/en-GB/games/box-party")],
    },
    {
        "slug": "star-crew",
        "title": "Star Crew",
        "client": "Earthrise One",
        "group": "rooms",
        "role": "Interactive Designer",
        "players": "2–6",
        "tech": ["MIDI touch consoles", "Microphone audio", "Real-time game"],
        "colour": "cyan",
        "hero": "star-crew.jpg",
        "summary": "A real-time space adventure where each player runs their own station on the bridge.",
        "about": [
            "Star Crew is a digitally enhanced game room for two to six players. Each player takes one of six roles on a spaceship and runs a touch console built on MIDI hardware. Crews talk to each other through a microphone-controlled audio system as they fly a real-time space adventure together.",
        ],
        "did": [
            "Designed the interactive game and the six crew roles",
            "Designed the touch interfaces built on MIDI hardware",
            "Designed how the crew communicates through microphones",
        ],
        "gallery": [],
        "links": [
            ("Earthrise One", "https://www.earthrise.one/star-crew"),
            ("Review", "https://www.mojonews.com.au/star-crew-escape-room-opens-review/"),
        ],
    },
    {
        "slug": "technomancers",
        "title": "Technomancers",
        "client": "Culture Jam",
        "group": "rooms",
        "role": "Experience Director",
        "year": "2025",
        "tech": ["Live performance", "Live music", "MIDI smart lights"],
        "colour": "purple",
        "hero": "technomancers.jpg",
        "summary": "Immersive theatre where the audience is guided by light, music and technology.",
        "about": [
            "Technomancers is an immersive theatre installation that combines live performance and live music with smart lights controlled over MIDI. The audience is led through a theatrical journey by the lights and technology around them.",
        ],
        "did": [
            "Wrote the show",
            "Co-performed in it",
            "Programmed the lights and all the technology",
        ],
        "gallery": [],
        "links": [("Culture Jam", "https://culturejam.com.au/events/questival/")],
    },
    {
        "slug": "the-thought-that-counts",
        "title": "The Thought that Counts",
        "client": "With Kitney Hartstone Productions",
        "group": "rooms",
        "role": "Designer & developer",
        "year": "2021",
        "tech": ["Arcade installation", "Group play"],
        "colour": "pink",
        "hero": "thought-that-counts.jpg",
        "award": "Weekly prize for Best Interactive Art, Adelaide Fringe 2021 · $10k SA Arts grant",
        "summary": "A mental-health arcade game where your group decides what a pixel bunny thinks.",
        "about": [
            "In The Thought that Counts, a group plays together to choose the thoughts of a pixel bunny going through a mental-health crisis. Players see how their choices shape its view of the world, how it falls into despair, and how friendship and love can pull it back.",
            "It ran as a pop-up installation at Adelaide Fringe and Adelaide City Library.",
        ],
        "did": [
            "Designed and programmed the whole game",
            "Won a $10,000 SA Arts grant to fund it",
            "Worked with a production team in Adelaide on the physical installation",
        ],
        "gallery": [],
        "links": [
            ("Review", "https://mindshare.org.au/review-the-thought-that-counts/"),
            ("CityMag feature", "https://www.indailysa.com.au/citymag/archive/2021/10/22/mind-invaders-the-arcade-game-offering-lessons-in-mental-health"),
        ],
    },
    {
        "slug": "ahead-of-the-game",
        "title": "Ahead of the Game",
        "client": "Movember",
        "group": "learning",
        "role": "Learning Experience Designer",
        "tech": ["Mobile app", "Group activity", "Learning design"],
        "colour": "yellow",
        "hero": "ahead-of-the-game.jpg",
        "summary": "A mental-health resilience program for young men, combining in-person and digital experiences.",
        "about": [
            "Ahead of the Game teaches young men strategies for resilience. It pairs an augmented group activity run in person with a self-directed mobile app.",
        ],
        "did": [
            "Designed the learning experience across the group activity and the app",
            "Worked with Movember's development and creative teams",
            "Worked with men's psychologists to get the content right",
        ],
        "gallery": [],
        "links": [("Ahead of the Game", "https://aheadofthegame.movember.com/about/")],
    },
    {
        "slug": "movember-conversations",
        "title": "Movember Conversations",
        "client": "Movember",
        "group": "learning",
        "role": "Learning Experience Designer",
        "year": "2021",
        "tech": ["Branching dialogue", "Interactive scenarios", "Web"],
        "colour": "orange",
        "hero": "conversations-hero.jpg",
        "summary": "Practise the hard conversation before you have it: simulated chats with a mate who's struggling.",
        "about": [
            "Movember Conversations is a free online tool that helps people feel more confident talking with a man in their life who might be struggling. Users pick a scenario, such as job loss, social isolation or family pressure, and work through a simulated conversation, choosing what to say at each step and seeing where it leads.",
            "It's built on the ALEC framework from R U OK? (Ask, Listen, Encourage action, Check in) and was developed with mental-health experts.",
        ],
        "did": [
            "Designed the interactive conversation format and the branching dialogue",
            "Worked with mental-health experts to turn the ALEC framework into scenarios people can practise",
            "Designed the learning experience across the scenarios",
        ],
        "gallery": [],
        "links": [("Try Movember Conversations", "https://conversations.movember.com/en/")],
    },
    {
        "slug": "family-man",
        "title": "Family Man",
        "client": "Movember",
        "group": "learning",
        "role": "Learning Experience Designer",
        "tech": ["Interactive video", "Branching narrative", "Online course"],
        "colour": "green",
        "hero": None,
        "summary": "A choose-your-own-adventure video game that teaches key parenting skills.",
        "about": [
            "Family Man is an online course built as a choose-your-own-adventure game. Parents make decisions through interactive video and see how different approaches play out.",
        ],
        "did": [
            "Designed the branching narrative and the game structure",
            "Worked with child-behaviour experts, artists and developers",
        ],
        "gallery": [],
        "links": [("Play Family Man", "https://familyman.movember.com/")],
    },
    {
        "slug": "gripable",
        "title": "GripAble",
        "client": "GripAble",
        "group": "learning",
        "role": "Senior UX Designer",
        "year": "2018–2021",
        "tech": ["Grip sensor controller", "Tablet app", "Rehab games"],
        "colour": "cyan",
        "hero": "gripable-hero.jpg",
        "summary": "Hand and arm rehabilitation turned into games you play by squeezing, releasing and turning a smart grip.",
        "about": [
            "GripAble is a handheld rehabilitation device that grew out of research at Imperial College London. Force and motion sensors pick up grip, release and wrist movement, so patients with weakness in the hand, wrist or arm can do their therapy by playing games on a tablet, while they and their clinicians track progress.",
        ],
        "did": [
            "Designed the app experience for patients and clinicians",
            "Designed games and interfaces controlled entirely by grip and wrist movement",
            "Designed for users with limited mobility, where every input costs effort",
        ],
        "gallery": ["gripable-2.jpg", "gripable-3.jpg"],
        "links": [("GripAble", "https://gripable.co/")],
    },
]

GROUPS = {
    "gamebox": "Immersive Gamebox",
    "rooms": "Installations & theatre",
    "learning": "Learning & health",
}
